# Generated by Django 2.2.6 on 2020-03-07 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appl_id', models.IntegerField()),
                ('value', models.CharField(choices=[('Accepted', 'Accept'), ('Rejected', 'Reject')], default='Rejected', max_length=8)),
                ('seen', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_name', models.CharField(max_length=200)),
                ('proj_cpi', models.FloatField(default=0.0)),
                ('proj_description', models.TextField(max_length=1000)),
                ('proj_dept', models.CharField(choices=[('cse', 'Computer Science and Engineering'), ('ece', 'Electronics & Commmunication  Engineering'), ('eee', 'Electrical & Electronics Engineering'), ('me', 'Mechanical Engineering'), ('cst', 'Chemical Science and Technology'), ('cl', 'Chemical Engineering'), ('mnc', 'Maths and Computing'), ('ce', 'Civil Engineering'), ('bt', 'Bio Technology'), ('ep', 'Engineering Physics')], max_length=3)),
                ('proj_status', models.CharField(choices=[('na', 'Not Assigned'), ('og', 'Ongoing'), ('cp', 'Completed')], default='na', max_length=2)),
                ('proj_prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
