# Generated by Django 2.2.6 on 2020-03-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elprofessor', '0002_auto_20200307_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accept',
            name='appl_id',
            field=models.IntegerField(null=True),
        ),
    ]
