# Generated by Django 2.2.6 on 2020-03-07 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.IntegerField()),
                ('department', models.CharField(choices=[('cse', 'Computer Science and Engineering'), ('ece', 'Electronics & Commmunication  Engineering'), ('eee', 'Electrical & Electronics Engineering'), ('me', 'Mechanical Engineering'), ('cst', 'Chemical Science and Technology'), ('cl', 'Chemical Engineering'), ('mnc', 'Maths and Computing'), ('ce', 'Civil Engineering'), ('bt', 'Bio Technology'), ('ep', 'Engineering Physics')], max_length=5)),
                ('student_name', models.CharField(max_length=100)),
                ('cpi', models.FloatField()),
                ('skills', models.TextField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_name', models.CharField(max_length=100)),
                ('prof_website', models.URLField(max_length=250)),
                ('prof_dept', models.CharField(choices=[('cse', 'Computer Science and Engineering'), ('ece', 'Electronics & Commmunication  Engineering'), ('eee', 'Electrical & Electronics Engineering'), ('me', 'Mechanical Engineering'), ('cst', 'Chemical Science and Technology'), ('cl', 'Chemical Engineering'), ('mnc', 'Maths and Computing'), ('ce', 'Civil Engineering'), ('bt', 'Bio Technology'), ('ep', 'Engineering Physics')], max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
