# Generated by Django 2.2.6 on 2020-03-07 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applyform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.IntegerField(default=0)),
                ('name', models.CharField(default='asd', max_length=100)),
                ('dept', models.CharField(choices=[('cse', 'Computer Science and Engineering'), ('ece', 'Electronics & Commmunication  Engineering'), ('eee', 'Electrical & Electronics Engineering'), ('me', 'Mechanical Engineering'), ('cst', 'Chemical Science and Technology'), ('cl', 'Chemical Engineering'), ('mnc', 'Maths and Computing'), ('ce', 'Civil Engineering'), ('bt', 'Bio Technology'), ('ep', 'Engineering Physics')], default='cse', max_length=5)),
                ('cpi', models.FloatField(default=0.0)),
                ('email', models.EmailField(default='abc@xyz.com', max_length=254)),
                ('cv', models.URLField(default='ac@bc.com')),
                ('bio', models.TextField(default='wish')),
                ('proj_id', models.IntegerField(default='1')),
            ],
        ),
        migrations.CreateModel(
            name='Intern_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(choices=[('cse', 'Computer Science and Engineering'), ('ece', 'Electronics & Commmunication  Engineering'), ('eee', 'Electrical & Electronics Engineering'), ('me', 'Mechanical Engineering'), ('cst', 'Chemical Science and Technology'), ('cl', 'Chemical Engineering'), ('mnc', 'Maths and Computing'), ('ce', 'Civil Engineering'), ('bt', 'Bio Technology'), ('ep', 'Engineering Physics')], max_length=5)),
                ('prof_name', models.CharField(max_length=100)),
                ('min_cpi', models.FloatField()),
                ('title', models.CharField(max_length=50)),
                ('skills', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='User_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginapp.Student')),
            ],
        ),
    ]
